name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10

    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: thevikramrajput
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
